### ISSUE TITLE
test failiures from a pytest/click issue

### ISSUE THREAD

**Issue by pombredanne** [kojiromike/parameter-expansion#31]
This is  https://github.com/psf/black/issues/2964
```
Traceback (most recent call last):
  File "/pc/clone/mv7KaCmETESj4PgRh21cwA/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/pc/clone/mv7KaCmETESj4PgRh21cwA/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1282, in patched_main
    patch_click()
  File "/pc/clone/mv7KaCmETESj4PgRh21cwA/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 1268, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/pc/clone/mv7KaCmETESj4PgRh21cwA/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

**Comment by pombredanne** [comment]
This is resolved upstream now. Closing
